kind = "mobile"
previewPath = "/mobile/"
title = "Interest Calculator Mobile"
version = "1.0.0"
id = "artifacts/interest-app"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 19169

[services.development]
run = "pnpm --filter @workspace/interest-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/interest-app", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/interest-app", "run", "serve" ]

[services.env]
PORT = "19169"
BASE_PATH = "/mobile/"
